[project]
name = "nikke-sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "pandas-stubs>=2.3.2.250926",
]
